version: '3.8'

services:
  test-container:
    container_name: test-container-1
    build:
      context: .
    environment:
      - PORT=1234
    ports:
      - "3000:1234"
    volumes:
      - "D:/Yniver/Four_curs_IT_7_semestr/Upravlenie_IT_proektami/Lab1/Lab1:/app/logs"

  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=bronnikovalexandr
      - POSTGRES_PASSWORD=84937
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  postgres_data:
  mongo_data:
  portainer_data:
